services:
  - type: web
    name: project-completion-tracker
    env: node
    plan: free
    buildCommand: cd backend && npm install && cd ../frontend && npm install --include=dev && npm run build && cd ../backend
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production 